sudo: required
services:
  - docker

before_install:
  - docker build -t manish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manish/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-724603171105"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
